markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6	
paginate_path: page/:num


# Build settings
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

#SyntaxHihglighter config start

SyntaxHihglighter: false
shTheme: shThemeDefault # shThemeDefault  shThemeDjango  shThemeEclipse  shThemeEmacs  shThemeFadeToGrey  shThemeMidnight  shThemeRDark

#SyntaxHihglighter config end

blog:
    name: 小米客栈                                          # 博客名称
    description: In love folly is always sweet                     # 博客描述
    title: 小米客栈主页                                         # 网页标题
    url: http://xmkz.github.io/                         # 博客地址
    duoshuo: xmkz                                       # 多说ID 
    tongji: 5e8682c146ae03037a189238a877953b             # 百度统计ID
    clickiTongJi: 					 # Clicki统计ID
    qiniu:                                               # 七牛云地址
author:
    name: VitaminZou                                          # 作者名称
    email: xiaomikezhan@gmail.com                                # 邮箱地址
    weibo: http://weibo.com/xmkz8                        # 微博地址
    github: https://github.com/                     # GitHub地址
    logo: /res/img/icon.jpg                              # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
